# Form implementation generated from reading ui file '.\demo.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1327, 701)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\__siesta_tantei_wa_mou_shindeiru_drawn_by_lua22__sample-6b25b3a8cf6b7de416ce0100826da1b4.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStatusTip("")
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    margin: 0;\n"
"    padding: 0;\n"
"    scrollbar-width: thin\n"
"}\n"
"\n"
"QSrollBar{\n"
"    border:none;\n"
"    background-color: rgb(161, 161, 161);\n"
"    margin: 0\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::add-line:horizontal, QScrollBar::sub-line:vertical, QScrollBar::sub-line:horizontal{\n"
"    border: none;\n"
"    background: none\n"
"}\n"
"\n"
"QScrollBar:handle{\n"
"    border:none;\n"
"    background-color: rgb(64, 65, 66);\n"
"    border-radius: 8%;\n"
"    width: 12px\n"
"}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal, QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"    border: none;\n"
"}\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical, QScrollBar:left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    border: none;\n"
"    background:none;\n"
" }\n"
"QScrollBar::handle:vertical:hover, QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(36, 36, 36);\n"
"}\n"
"QScrollBar::handle:vertical:pressed, QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(24,24,24);\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"    margin: 0;\n"
"    padding: 0;\n"
"    border: none\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.categories = QtWidgets.QFrame(parent=self.centralwidget)
        self.categories.setMaximumSize(QtCore.QSize(16777215, 100))
        self.categories.setStyleSheet("*{\n"
"    border:none;\n"
"    background:     #3e3e42;\n"
"    color: white;\n"
"    margin: 0;\n"
"    padding: 0;\n"
"}\n"
"\n"
"QPushButton{\n"
"    text-decoration: underline;\n"
"    font-size: 14px;\n"
"    font: 10pt url(\'https://fonts.googleapis.com/css2?family=Oswald:wght@500&family=Roboto:wght@300&display=swap\');\n"
"}\n"
"\n"
".QFrame#categories{\n"
"    width:100%;\n"
"    padding: 0;\n"
"    border:100px\n"
"}")
        self.categories.setObjectName("categories")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.categories)
        self.gridLayout_2.setContentsMargins(0, 0, -1, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.app_icon = QtWidgets.QLabel(parent=self.categories)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.app_icon.sizePolicy().hasHeightForWidth())
        self.app_icon.setSizePolicy(sizePolicy)
        self.app_icon.setMinimumSize(QtCore.QSize(94, 90))
        self.app_icon.setMaximumSize(QtCore.QSize(94, 94))
        self.app_icon.setText("")
        self.app_icon.setPixmap(QtGui.QPixmap(".\\assets/c2809fdd51f6ea93032bfed10dcf824b.png"))
        self.app_icon.setScaledContents(True)
        self.app_icon.setWordWrap(True)
        self.app_icon.setIndent(-1)
        self.app_icon.setObjectName("app_icon")
        self.gridLayout_2.addWidget(self.app_icon, 0, 0, 4, 2, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.category_container = QtWidgets.QHBoxLayout()
        self.category_container.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.category_container.setContentsMargins(0, 10, 0, 0)
        self.category_container.setSpacing(70)
        self.category_container.setObjectName("category_container")
        self.Economy = QtWidgets.QPushButton(parent=self.categories)
        self.Economy.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Economy.setObjectName("Economy")
        self.category_container.addWidget(self.Economy)
        self.Politics = QtWidgets.QPushButton(parent=self.categories)
        self.Politics.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Politics.setObjectName("Politics")
        self.category_container.addWidget(self.Politics)
        self.Traffic = QtWidgets.QPushButton(parent=self.categories)
        self.Traffic.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Traffic.setObjectName("Traffic")
        self.category_container.addWidget(self.Traffic)
        self.Medical = QtWidgets.QPushButton(parent=self.categories)
        self.Medical.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Medical.setObjectName("Medical")
        self.category_container.addWidget(self.Medical)
        self.Sport = QtWidgets.QPushButton(parent=self.categories)
        self.Sport.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Sport.setObjectName("Sport")
        self.category_container.addWidget(self.Sport)
        self.Travel = QtWidgets.QPushButton(parent=self.categories)
        self.Travel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Travel.setObjectName("Travel")
        self.category_container.addWidget(self.Travel)
        self.Entertain = QtWidgets.QPushButton(parent=self.categories)
        self.Entertain.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Entertain.setObjectName("Entertain")
        self.category_container.addWidget(self.Entertain)
        self.SciTech = QtWidgets.QPushButton(parent=self.categories)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SciTech.sizePolicy().hasHeightForWidth())
        self.SciTech.setSizePolicy(sizePolicy)
        self.SciTech.setBaseSize(QtCore.QSize(0, 0))
        self.SciTech.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.SciTech.setObjectName("SciTech")
        self.category_container.addWidget(self.SciTech)
        self.category_container.setStretch(0, 1)
        self.category_container.setStretch(1, 1)
        self.category_container.setStretch(2, 1)
        self.category_container.setStretch(3, 1)
        self.category_container.setStretch(4, 1)
        self.category_container.setStretch(5, 1)
        self.category_container.setStretch(6, 1)
        self.category_container.setStretch(7, 2)
        self.gridLayout_2.addLayout(self.category_container, 2, 3, 1, 1)
        self.app_name = QtWidgets.QLabel(parent=self.categories)
        self.app_name.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.app_name.setFont(font)
        self.app_name.setObjectName("app_name")
        self.gridLayout_2.addWidget(self.app_name, 1, 3, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.user_action = QtWidgets.QWidget(parent=self.categories)
        self.user_action.setObjectName("user_action")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.user_action)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.login = QtWidgets.QPushButton(parent=self.user_action)
        self.login.setMaximumSize(QtCore.QSize(100, 16777215))
        self.login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.login.setStyleSheet("*{\n"
"    color: white\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\user (3).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.login.setIcon(icon1)
        self.login.setObjectName("login")
        self.horizontalLayout_2.addWidget(self.login)
        self.register_2 = QtWidgets.QPushButton(parent=self.user_action)
        self.register_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.register_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.register_2.setStyleSheet("*{\n"
"    color: white\n"
"}")
        self.register_2.setIcon(icon1)
        self.register_2.setObjectName("register_2")
        self.horizontalLayout_2.addWidget(self.register_2)
        self.gridLayout_2.addWidget(self.user_action, 0, 4, 1, 1)
        self.verticalLayout_7.addWidget(self.categories)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1327, 601))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.older_news = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.older_news.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.older_news.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.older_news.setObjectName("older_news")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.older_news)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.hot_news_label_3 = QtWidgets.QLabel(parent=self.older_news)
        self.hot_news_label_3.setMinimumSize(QtCore.QSize(711, 32))
        self.hot_news_label_3.setMaximumSize(QtCore.QSize(711, 32))
        self.hot_news_label_3.setAutoFillBackground(False)
        self.hot_news_label_3.setObjectName("hot_news_label_3")
        self.verticalLayout_12.addWidget(self.hot_news_label_3)
        self.old_1 = QtWidgets.QFrame(parent=self.older_news)
        self.old_1.setMaximumSize(QtCore.QSize(1204, 181))
        self.old_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.old_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.old_1.setObjectName("old_1")
        self.formLayout_5 = QtWidgets.QFormLayout(self.old_1)
        self.formLayout_5.setObjectName("formLayout_5")
        self.old_1_image = QtWidgets.QLabel(parent=self.old_1)
        self.old_1_image.setMaximumSize(QtCore.QSize(391, 181))
        self.old_1_image.setText("")
        self.old_1_image.setPixmap(QtGui.QPixmap(".\\assets/Screenshot (14).png"))
        self.old_1_image.setScaledContents(True)
        self.old_1_image.setObjectName("old_1_image")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.old_1_image)
        self.old_1_set = QtWidgets.QFrame(parent=self.old_1)
        self.old_1_set.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.old_1_set.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.old_1_set.setObjectName("old_1_set")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.old_1_set)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.old_1_title = QtWidgets.QLabel(parent=self.old_1_set)
        self.old_1_title.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.old_1_title.setFont(font)
        self.old_1_title.setObjectName("old_1_title")
        self.verticalLayout_8.addWidget(self.old_1_title)
        self.old_1_description = QtWidgets.QLabel(parent=self.old_1_set)
        self.old_1_description.setMinimumSize(QtCore.QSize(0, 0))
        self.old_1_description.setMaximumSize(QtCore.QSize(16777215, 100))
        self.old_1_description.setStyleSheet("*{\n"
"    background-color: white\n"
"}")
        self.old_1_description.setWordWrap(True)
        self.old_1_description.setObjectName("old_1_description")
        self.verticalLayout_8.addWidget(self.old_1_description)
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.old_1_set)
        self.verticalLayout_12.addWidget(self.old_1)
        self.verticalLayout.addWidget(self.older_news)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Newspaper App"))
        self.Economy.setText(_translate("MainWindow", "Economy"))
        self.Politics.setText(_translate("MainWindow", "Politics"))
        self.Traffic.setText(_translate("MainWindow", "Traffic"))
        self.Medical.setText(_translate("MainWindow", "Medical"))
        self.Sport.setText(_translate("MainWindow", "Sport"))
        self.Travel.setText(_translate("MainWindow", "Travel"))
        self.Entertain.setText(_translate("MainWindow", "Entertain"))
        self.SciTech.setText(_translate("MainWindow", "Science and Technology"))
        self.app_name.setText(_translate("MainWindow", "TOMATO NEWS"))
        self.login.setText(_translate("MainWindow", "Login"))
        self.register_2.setText(_translate("MainWindow", "Register"))
        self.hot_news_label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">CATEGORY NAME</span></p></body></html>"))
        self.old_1_title.setText(_translate("MainWindow", "SAMPLE TITLE"))
        self.old_1_description.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Lorem Ipsum</span><span style=\" font-size:10pt;\"> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
