# Form implementation generated from reading ui file '.\login\register.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UI_Register(object):
    def setupUi(self, RegisterWindow, npcallback):
        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.resize(403, 470)
        RegisterWindow.setMinimumSize(QtCore.QSize(392, 369))
        RegisterWindow.setMaximumSize(QtCore.QSize(510, 500))
        RegisterWindow.setStyleSheet(".QLineEdit{\n"
"    width: 250%;\n"
"    height: auto;\n"
"    border:none;\n"
"    border-bottom: 1px solid black\n"
"}\n"
".QPushButton{\n"
"    background-color: rgb(1, 124, 255);\n"
"    border-radius: 5px;\n"
"    width: 80%;\n"
"    height: auto;\n"
"    color: white;\n"
"    border:none\n"
"}\n"
".QPushButton:focus{\n"
"    background-color: rgb(0, 50, 255);\n"
"    border: none\n"
"}\n"
"*{\n"
"    background-color: rgb(255,255,255);\n"
"    margin: 0\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=RegisterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 160))
        self.title_frame.setStyleSheet("background-color: rgb(42, 42, 42);\n"
"color: white")
        self.title_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.title_frame.setObjectName("title_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title_txt = QtWidgets.QLabel(parent=self.title_frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title_txt.setFont(font)
        self.title_txt.setObjectName("title_txt")
        self.horizontalLayout.addWidget(self.title_txt, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout.addWidget(self.title_frame)
        self.name_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.name_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.name_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.name_frame.setObjectName("name_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.name_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.name_txt = QtWidgets.QLabel(parent=self.name_frame)
        self.name_txt.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.name_txt.setFont(font)
        self.name_txt.setObjectName("name_txt")
        self.verticalLayout_2.addWidget(self.name_txt)
        self.name_input = QtWidgets.QLineEdit(parent=self.name_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name_input.setFont(font)
        self.name_input.setObjectName("name_input")
        self.verticalLayout_2.addWidget(self.name_input)
        self.verticalLayout.addWidget(self.name_frame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.username_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.username_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.username_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.username_frame.setObjectName("username_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.username_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.username_txt = QtWidgets.QLabel(parent=self.username_frame)
        self.username_txt.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.username_txt.setFont(font)
        self.username_txt.setObjectName("username_txt")
        self.verticalLayout_4.addWidget(self.username_txt)
        self.username_input = QtWidgets.QLineEdit(parent=self.username_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.username_input.setFont(font)
        self.username_input.setObjectName("username_input")
        self.verticalLayout_4.addWidget(self.username_input)
        self.verticalLayout.addWidget(self.username_frame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.pwrd_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.pwrd_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pwrd_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pwrd_frame.setObjectName("pwrd_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pwrd_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pwrd_txt = QtWidgets.QLabel(parent=self.pwrd_frame)
        self.pwrd_txt.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pwrd_txt.setFont(font)
        self.pwrd_txt.setObjectName("pwrd_txt")
        self.verticalLayout_3.addWidget(self.pwrd_txt)
        self.pwrd_input = QtWidgets.QLineEdit(parent=self.pwrd_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pwrd_input.setFont(font)
        self.pwrd_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.pwrd_input.setObjectName("pwrd_input")
        self.verticalLayout_3.addWidget(self.pwrd_input)
        self.verticalLayout.addWidget(self.pwrd_frame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        # Call register (callback) when button is clicked
        self.registerButton = QtWidgets.QPushButton(parent=self.centralwidget, clicked=lambda: self.controller_register(npcallback) )
        self.registerButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.registerButton.setObjectName("registerButton")
        self.verticalLayout.addWidget(self.registerButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        
        self.result_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.result_label.setObjectName("resultLabel")
        self.result_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.verticalLayout.addWidget(self.result_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        
        RegisterWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)

    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "MainWindow"))
        self.title_txt.setText(_translate("RegisterWindow", "Register to become an Author"))
        self.name_txt.setText(_translate("RegisterWindow", "Full Name"))
        self.username_txt.setText(_translate("RegisterWindow", "Username"))
        self.pwrd_txt.setText(_translate("RegisterWindow", "Password"))
        self.registerButton.setText(_translate("RegisterWindow", "Register"))

    def controller_register(self, register_callback):
        real_name = self.name_input.text()
        username = self.username_input.text()
        password = self.pwrd_input.text()

        res = register_callback(username, password, real_name)
        if res:
            self.result_label.setText("Register successful")
        else:
            self.result_label.setText("The username is already taken. Please try another one.")
